# Taint Sources
# Paths matching these patterns trigger taint marking
# Level determines how aggressively to block subsequent operations

sources:
  # Critical secrets - highest protection
  - pattern: ".secrets/*"
    level: "critical"
    description: "Secrets directory"

  - pattern: "id_rsa*"
    level: "critical"
    description: "SSH private keys"

  - pattern: "*.pem"
    level: "critical"
    description: "Certificate/key files"

  - pattern: "*.key"
    level: "critical"
    description: "Key files"

  # High sensitivity
  - pattern: "*.env"
    level: "high"
    description: "Environment files"

  - pattern: "*.env.*"
    level: "high"
    description: "Environment variant files"

  - pattern: "credentials.*"
    level: "high"
    description: "Credentials files"

  # Medium sensitivity
  - pattern: "*.crt"
    level: "medium"
    description: "Certificate files"

  - pattern: ".netrc"
    level: "medium"
    description: "Netrc file"

  - pattern: "_netrc"
    level: "medium"
    description: "Windows netrc file"
